package server

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/polds/rapid-issue-triage/internal/store"
)

var verdictLabels = map[string]string{
	"actionable":        "Still actionable",
	"likely_obsolete":   "Likely obsolete",
	"possibly_done":     "Possibly already done",
	"needs_info":        "Needs more info",
	"duplicate_suspect": "Duplicate suspect",
}

var urlRe = regexp.MustCompile(`^https?://`)

// formatEnrichmentComment renders an issue's stored enrichment as Linear
// markdown: the full structured report when a deep run exists, otherwise the
// fast summary. Mirrors the frontend's formatReportComment.
func formatEnrichmentComment(e *store.Enrichment) (string, error) {
	if e == nil || (e.Summary == "" && len(e.Report) == 0) {
		return "", fmt.Errorf("no AI enrichment on this issue yet — enrich it first")
	}
	var lines []string
	label := verdictLabels[e.Verdict]
	if label == "" {
		label = e.Verdict
	}

	if len(e.Report) > 0 {
		var r struct {
			Verdict        string  `json:"verdict"`
			Confidence     float64 `json:"confidence"`
			Summary        string  `json:"summary"`
			Reasoning      string  `json:"reasoning"`
			Recommendation string  `json:"recommendation"`
			Evidence       []struct {
				Source  string `json:"source"`
				Finding string `json:"finding"`
				Link    string `json:"link"`
			} `json:"evidence"`
			RelatedIssues []struct {
				Identifier string `json:"identifier"`
				State      string `json:"state"`
			} `json:"relatedIssues"`
			RelatedPRs []struct {
				Repo   string `json:"repo"`
				Number int    `json:"number"`
				State  string `json:"state"`
				URL    string `json:"url"`
			} `json:"relatedPRs"`
		}
		if err := json.Unmarshal(e.Report, &r); err == nil && r.Summary != "" {
			if l := verdictLabels[r.Verdict]; l != "" {
				label = l
			}
			lines = append(lines,
				fmt.Sprintf("**AI triage report — %s** (%d%% confidence)", label, int(r.Confidence*100)),
				"", r.Summary)
			if r.Reasoning != "" {
				lines = append(lines, "", "**Reasoning:** "+r.Reasoning)
			}
			if r.Recommendation != "" {
				lines = append(lines, "", "**Recommendation:** "+r.Recommendation)
			}
			if len(r.Evidence) > 0 {
				lines = append(lines, "", "**Evidence**")
				for _, ev := range r.Evidence {
					link := ""
					if ev.Link != "" {
						if urlRe.MatchString(ev.Link) {
							link = fmt.Sprintf(" ([link](%s))", ev.Link)
						} else {
							link = fmt.Sprintf(" (`%s`)", ev.Link)
						}
					}
					lines = append(lines, fmt.Sprintf("- **%s** — %s%s", ev.Source, ev.Finding, link))
				}
			}
			if len(r.RelatedPRs) > 0 {
				var prs []string
				for _, pr := range r.RelatedPRs {
					if pr.URL != "" {
						prs = append(prs, fmt.Sprintf("[%s#%d](%s) (%s)", pr.Repo, pr.Number, pr.URL, pr.State))
					} else {
						prs = append(prs, fmt.Sprintf("%s#%d (%s)", pr.Repo, pr.Number, pr.State))
					}
				}
				lines = append(lines, "", "**Related PRs:** "+strings.Join(prs, " · "))
			}
			if len(r.RelatedIssues) > 0 {
				var ris []string
				for _, ri := range r.RelatedIssues {
					ris = append(ris, fmt.Sprintf("%s (%s)", ri.Identifier, ri.State))
				}
				lines = append(lines, "", "**Related issues:** "+strings.Join(ris, " · "))
			}
			lines = append(lines, "", "*Generated by Rapid Triage deep enrichment.*")
			return strings.Join(lines, "\n"), nil
		}
	}

	// Fast enrichment only.
	lines = append(lines,
		fmt.Sprintf("**AI triage summary — %s** (%d%% confidence)", label, int(e.Confidence*100)),
		"", e.Summary)
	if e.Reasoning != "" {
		lines = append(lines, "", "**Reasoning:** "+e.Reasoning)
	}
	lines = append(lines, "", "*Generated by Rapid Triage AI enrichment.*")
	return strings.Join(lines, "\n"), nil
}
