package server

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/polds/rapid-issue-triage/internal/store"
)

var verdictLabels = map[string]string{
	"actionable":        "Still actionable",
	"likely_obsolete":   "Likely obsolete",
	"possibly_done":     "Possibly already done",
	"needs_info":        "Needs more info",
	"duplicate_suspect": "Duplicate suspect",
}

var urlRe = regexp.MustCompile(`^https?://`)
var linearIssuePrefix = regexp.MustCompile(`^(https://linear\.app/[^/]+/issue/)`)

func linearIssueURL(identifier, fromIssueURL, explicit string) string {
	if urlRe.MatchString(explicit) {
		return explicit
	}
	if identifier == "" || fromIssueURL == "" {
		return ""
	}
	m := linearIssuePrefix.FindStringSubmatch(fromIssueURL)
	if len(m) != 2 {
		return ""
	}
	return m[1] + identifier
}

// formatEnrichmentComment renders an issue's stored enrichment as Linear
// markdown: the full structured report when a deep run exists, otherwise the
// fast summary. Mirrors the frontend's formatReportComment.
func formatEnrichmentComment(e *store.Enrichment, issueURL string) (string, error) {
	if e == nil || (e.Summary == "" && len(e.Report) == 0) {
		return "", fmt.Errorf("no AI enrichment on this issue yet — enrich it first")
	}
	label := verdictLabels[e.Verdict]
	if label == "" {
		label = e.Verdict
	}
	if body, ok := formatDeepReport(e.Report, label, issueURL); ok {
		return body, nil
	}
	return formatFastSummary(e, label), nil
}

type deepReport struct {
	Verdict        string  `json:"verdict"`
	Confidence     float64 `json:"confidence"`
	Summary        string  `json:"summary"`
	Reasoning      string  `json:"reasoning"`
	Recommendation string  `json:"recommendation"`
	Evidence       []struct {
		Source  string `json:"source"`
		Finding string `json:"finding"`
		Link    string `json:"link"`
	} `json:"evidence"`
	RelatedIssues []struct {
		Identifier string `json:"identifier"`
		State      string `json:"state"`
		URL        string `json:"url"`
	} `json:"relatedIssues"`
	RelatedPRs []struct {
		Repo   string `json:"repo"`
		Number int    `json:"number"`
		State  string `json:"state"`
		URL    string `json:"url"`
	} `json:"relatedPRs"`
}

func formatDeepReport(raw json.RawMessage, label, issueURL string) (string, bool) {
	if len(raw) == 0 {
		return "", false
	}
	var r deepReport
	if err := json.Unmarshal(raw, &r); err != nil || r.Summary == "" {
		return "", false
	}
	if l := verdictLabels[r.Verdict]; l != "" {
		label = l
	}
	lines := []string{
		fmt.Sprintf("**AI triage report — %s** (%d%% confidence)", label, int(r.Confidence*100)),
		"", r.Summary,
	}
	if r.Reasoning != "" {
		lines = append(lines, "", "**Reasoning:** "+r.Reasoning)
	}
	if r.Recommendation != "" {
		lines = append(lines, "", "**Recommendation:** "+r.Recommendation)
	}
	lines = appendEvidence(lines, r)
	lines = appendRelated(lines, r, issueURL)
	lines = append(lines, "", "*Generated by Rapid Triage deep enrichment.*")
	return strings.Join(lines, "\n"), true
}

func appendEvidence(lines []string, r deepReport) []string {
	if len(r.Evidence) == 0 {
		return lines
	}
	lines = append(lines, "", "**Evidence**")
	for _, ev := range r.Evidence {
		link := ""
		if ev.Link != "" && urlRe.MatchString(ev.Link) {
			link = fmt.Sprintf(" ([link](%s))", ev.Link)
		} else if ev.Link != "" {
			link = fmt.Sprintf(" (`%s`)", ev.Link)
		}
		lines = append(lines, fmt.Sprintf("- **%s** — %s%s", ev.Source, ev.Finding, link))
	}
	return lines
}

func appendRelated(lines []string, r deepReport, issueURL string) []string {
	if len(r.RelatedPRs) > 0 {
		prs := make([]string, 0, len(r.RelatedPRs))
		for _, pr := range r.RelatedPRs {
			if pr.URL != "" {
				prs = append(prs, fmt.Sprintf("[%s#%d](%s) (%s)", pr.Repo, pr.Number, pr.URL, pr.State))
			} else {
				prs = append(prs, fmt.Sprintf("%s#%d (%s)", pr.Repo, pr.Number, pr.State))
			}
		}
		lines = append(lines, "", "**Related PRs:** "+strings.Join(prs, " · "))
	}
	if len(r.RelatedIssues) > 0 {
		ris := make([]string, 0, len(r.RelatedIssues))
		for _, ri := range r.RelatedIssues {
			if href := linearIssueURL(ri.Identifier, issueURL, ri.URL); href != "" {
				ris = append(ris, fmt.Sprintf("[%s](%s) (%s)", ri.Identifier, href, ri.State))
			} else {
				ris = append(ris, fmt.Sprintf("%s (%s)", ri.Identifier, ri.State))
			}
		}
		lines = append(lines, "", "**Related issues:** "+strings.Join(ris, " · "))
	}
	return lines
}

func formatFastSummary(e *store.Enrichment, label string) string {
	lines := []string{
		fmt.Sprintf("**AI triage summary — %s** (%d%% confidence)", label, int(e.Confidence*100)),
		"", e.Summary,
	}
	if e.Reasoning != "" {
		lines = append(lines, "", "**Reasoning:** "+e.Reasoning)
	}
	lines = append(lines, "", "*Generated by Rapid Triage AI enrichment.*")
	return strings.Join(lines, "\n")
}
