// Verdict presentation metadata and the Linear-flavored markdown rendering
// of a deep report. Kept out of DeepPanel.tsx so that module exports only
// components and stays fast-refresh friendly.
import type { DeepReport } from "@/lib/types";
import { linearIssueHref } from "@/lib/linear";

export const VERDICT_META: Record<string, { label: string; tone: string }> = {
  actionable: { label: "Still actionable", tone: "border-success/35 bg-success/10 text-success" },
  likely_obsolete: { label: "Likely obsolete", tone: "border-destructive/35 bg-destructive/10 text-destructive" },
  possibly_done: { label: "Possibly already done", tone: "border-info/35 bg-info/10 text-info" },
  needs_info: { label: "Needs more info", tone: "border-info/35 bg-info/10 text-info" },
  duplicate_suspect: {
    label: "Duplicate suspect",
    tone: "border-warning/45 bg-warning/15 text-warning-foreground dark:text-warning",
  },
};

// formatReportComment renders the deep report as Linear-flavored markdown
// suitable for posting back as a comment. issueUrl (the current issue's
// Linear URL) is used to turn related-issue identifiers into links.
export function formatReportComment(r: DeepReport, issueUrl?: string): string {
  const v = VERDICT_META[r.verdict]?.label ?? r.verdict;
  const lines: string[] = [];
  lines.push(`**AI triage report — ${v}** (${Math.round((r.confidence ?? 0) * 100)}% confidence)`);
  lines.push("");
  lines.push(r.summary);
  if (r.reasoning) {
    lines.push("");
    lines.push(`**Reasoning:** ${r.reasoning}`);
  }
  if (r.recommendation) {
    lines.push("");
    lines.push(`**Recommendation:** ${r.recommendation}`);
  }
  if (r.evidence?.length) {
    lines.push("");
    lines.push("**Evidence**");
    for (const e of r.evidence) {
      const link = e.link ? (/^https?:/.test(e.link) ? ` ([link](${e.link}))` : ` (\`${e.link}\`)`) : "";
      lines.push(`- **${e.source}** — ${e.finding}${link}`);
    }
  }
  if (r.relatedPRs?.length) {
    lines.push("");
    lines.push(
      "**Related PRs:** " +
        r.relatedPRs
          .map((pr) => (pr.url ? `[${pr.repo}#${pr.number}](${pr.url}) (${pr.state})` : `${pr.repo}#${pr.number} (${pr.state})`))
          .join(" · "),
    );
  }
  if (r.relatedIssues?.length) {
    lines.push("");
    lines.push(
      "**Related issues:** " +
        r.relatedIssues
          .map((ri) => {
            const href = linearIssueHref(ri.identifier, issueUrl, ri.url);
            return href ? `[${ri.identifier}](${href}) (${ri.state})` : `${ri.identifier} (${ri.state})`;
          })
          .join(" · "),
    );
  }
  lines.push("");
  lines.push("*Generated by Rapid Triage deep enrichment.*");
  return lines.join("\n");
}
